
So I now have a Retina MacBook Pro, named iris after Iris Murdoch.  All my laptops have been named after 20th/21st century philosophers: 

| name    | philosopher         | machine             |
|---------+---------------------+---------------------|
| gottlob | Gottlob Frege       | IBM Thinkpad        |
| ludwig  | Ludwig Wittgenstein | PowerBook G4        |
| bert    | Bertrand Russell    | MacBook Pro         |
| willard | W. V. O. Quine      | iMac                |
| slavoj  | Slavoj Žižek        | MacBook Pro unibody |
| iris    | Iros Murdoch        | Retina MacBook Pro  |
|         |                     |                     |

* Software to install on a new Mac

** Inital stages - App store, Dropbox, 1Password
+ Apps from the App Store are easy
  + Just log on with your Apple ID and get them from the App Store app. 
** Python 
+ Install Enthought's Canopy distribution
  + https://www.enthought.com/products/canopy/
  + Get 64-bit version
  + Free Academic License (requires registration using an academic email address) 
+ Run Canopy.app to set up as default python installation
  + This adds a line to =~/.profile= that sources their activation script
  + By default it esses with your prompt.  To fix this, add the following line to =~/.profile=
    #+BEGIN_SRC sh
# Stop Canopy from messing with $PS1
export VIRTUAL_ENV_DISABLE_PROMPT=y
    #+END_SRC
+ Use package manager ro install all Canopy packages
+ Other packages need to be installed by hand
  #+BEGIN_SRC sh
    easy_install pip
    pip install astropy
    pip install elpy
    pip install rope
    pip install jedi
    pip install pyregion
  #+END_SRC
+ Some need to be built from source
  + [X] scikit-image was problematic
    + Canopy had version 0.5 for some reason, which is wat to old (didn't have =morpholoy.dilate=, which I use a lot. 
    + The latest version on pypi was 0.8, but this seems to have a bug
    + So grab latest dev version (0.9dev at time of writing)
      #+BEGIN_SRC sh
        cd ~/Source
        git clone http://github.com/scikit-image/scikit-image.git
      #+END_SRC
      And build and install it
      #+BEGIN_SRC sh
        cd ~/Source/scikit-image
        python setup.py build
        python setup.py install
      #+END_SRC
** Fonts
*** Courier Prime
+ http://quoteunquoteapps.com/courierprime/
+ This font was designed for writing movie scripts, but it is a great general-purpose monospace font.
+ It comes with regular, /italic/, *bold*, and /*bold italic*/ versions. 
+ It is much more robust looking than the standard Courier, which always looked too spindly to me.
+ On a retina display, it is perfectly legible as small as 9 pt, although you probably want it bigger than that.
** Utilities
*** Moom - Window Control
*** Mailplane
*** 1Password

** Consumer software

** System software

*** rsync
+ OS X already has rsync, but it is version 2.6.9 from 2008!
  + In particular, it doesn't copy extended attributes properly
  + This is important since I don't want to lose any metadata when I copy over files from my old laptop.
+ So I install the latest version via homebrew:
  #+BEGIN_SRC sh
brew tap homebrew/dupes
brew info libiconv
brew install homebrew/dupes/libiconv
brew install homebrew/dupes/rsync
  #+END_SRC
+ Note that to use it, it is necessary to give the full path, since =/usr/bin= is before =/usr/local/bin= in y =$PATH=
  #+BEGIN_SRC sh :results verbatim 
rsync --version
  #+END_SRC

  #+RESULTS:
  #+BEGIN_EXAMPLE
  rsync  version 2.6.9  protocol version 29
  Copyright (C) 1996-2006 by Andrew Tridgell, Wayne Davison, and others.
  <http://rsync.samba.org/>
  Capabilities: 64-bit files, socketpairs, hard links, symlinks, batchfiles,
                inplace, IPv6, 64-bit system inums, 64-bit internal inums
  
  rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
  are welcome to redistribute it under certain conditions.  See the GNU
  General Public Licence for details.
  #+END_EXAMPLE
 
  #+BEGIN_SRC sh :results verbatim 
/usr/local/bin/rsync --version
  #+END_SRC

  #+RESULTS:
  #+begin_example
  rsync  version 3.0.9  protocol version 30
  Copyright (C) 1996-2011 by Andrew Tridgell, Wayne Davison, and others.
  Web site: http://rsync.samba.org/
  Capabilities:
      64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
      socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
      append, ACLs, xattrs, iconv, symtimes, file-flags

  rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
  are welcome to redistribute it under certain conditions.  See the GNU
  General Public Licence for details.
  #+end_example


** Science

*** DONE Bibdesk
CLOSED: [2013-05-16 Thu 16:35]
+ Installed without any trouble
+ [X] But having problems with the relative paths to attached PDFs
  + [X] First problem was with symbilic link on slavoj pointing back from Dropbox to local folder
    + [X] Fixed that by having Dropbox contain the real folder with symbolic link /from/ local folder
  + [X] Second problem is with files that have a literal "\" somewhere in the path
    + These are quite common in the autogenerated names of the PDF files. The chief culprits are:
      1. "\i" in author name - other accented characters get converted to UTF-8 fine
      2. Things like "\﻿mu" in the paper title (by the way, there is a "zero width no-break space" after the \ to fool org-mode into not rendering it as \mu).
    + It seems that Dropbox simply ignores these files, they are not synched at all.
    + [X] So we will have to fix the filenames so they don't contain the "\".
      + [X] This is now fixed on iris
        + I have switched over to a more sensible file naming scheme, =Author/CiteKey-N.pdf=, which also removes all special characters.
        + Example: =Henney/Henney2013a-0.pdf=
      + [X] Hopefuly, this can be done by tweaking Bibdesk settings on slavoj - not sure how easily.
        + [X] Quit BibDesk on iris
        + [X] Copy over the configuration from iris to slavoj
          + =/Users/will/Library/Preferences/edu.ucsd.cs.mmccrack.bibdesk.plist=
        + [X] Consolidate all the files on slavoj
          + =Shift-Cmd-K= I think
          + This should replace all the problematic paths with nice clean ones that DropBox can sync.
        + [X] Do I want to regenerate cite keys first?  Yes, I did this, so I will have to update all my latex doc to use the new cite keys. 
          

        


*** SAOImage ds9
+ Installed the latest binary distribution
+ But only runs when started from the installation directory


* [1/3] Transferring my files from slavoj
+ [X] I decided not just to copy over everything blindly with the migration assistant.
  + I did actually try to use Migration Assistant to copy over my just my home directory, but it was going to take 4 hours (even over thunderbolt) and there is no way of suspending it halfway through and resuming.
  + [X] I need to find out where it was writing its files and delete them, since I am pretty sure that it didn't clean up
    + [X] Run DaisyDisk to find big folders
    + [X] Turns out that it did clean up after all
      + The only large system folder (18GB) contains the sleep image
+ [ ] Instead I am using rsync to copy my home directory
  + I tried it over the network, but that didn't work
  + But it works fine with the old laptop connected via thunderbolt in "Target Disk Mode".
  + Command options used:
    #+BEGIN_SRC sh
    rsync -avPX 
    #+END_SRC
  + [2/9] Folders I am copying over (in order of last access date)
    + [X] ~/Admin/ very small
    + [X] ~/Work/ pretty big (176 GB)
      + All copied [2013-05-03 Fri 11:35]
    + [ ] ~/Documents
      + [ ] Do I really want all of this?
      + Certainly want Web Receipts
    + [ ] ~/Source
    + [ ] ~/bin
      + Mostly junk, but some useful things
    + [ ] ~/Teaching
    + [ ] ~/RMAA
    + [ ] *Hidden folders*
      + [ ] Need to check these in dired or terminal since they don't show up in Finder
    + [ ] 
+ [ ] How to deal with iTunes Library?
  + [ ] Probably best to temporarily set the Library file in iTunes to be the old laptop's iTunes Library, and then do "Consolidate Library"
