
So I now have a Retina MacBook Pro, named iris after Iris Murdoch.  All my laptops have been named after 20th/21st century philosophers: 

| name    | philosopher         | machine             |
|---------+---------------------+---------------------|
| gottlob | Gottlob Frege       | IBM Thinkpad        |
| ludwig  | Ludwig Wittgenstein | PowerBook G4        |
| bert    | Bertrand Russell    | MacBook Pro         |
| willard | W. V. O. Quine      | iMac                |
| slavoj  | Slavoj Žižek        | MacBook Pro unibody |
| iris    | Iros Murdoch        | Retina MacBook Pro  |
|         |                     |                     |

* Software to install on a new Mac

** Inital stages - App store, Dropbox, 1Password
+ Apps from the App Store are easy
  + Just log on with your Apple ID and get them from the App Store app. 
** Python 
+ Install Enthought's Canopy distribution
  + https://www.enthought.com/products/canopy/
  + Get 64-bit version
  + Free Academic License (requires registration using an academic email address) 
+ Run Canopy.app to set up as default python installation
  + This adds a line to =~/.profile= that sources their activation script
  + By default it esses with your prompt.  To fix this, add the following line to =~/.profile=
    #+BEGIN_SRC sh
# Stop Canopy from messing with $PS1
export VIRTUAL_ENV_DISABLE_PROMPT=y
    #+END_SRC
+ Use package manager ro install all Canopy packages
+ Other packages need to be installed by hand
  #+BEGIN_SRC sh
    easy_install pip
    pip install astropy
    pip install elpy
    pip install rope
    pip install jedi
    pip install pyregion
  #+END_SRC
+ Some need to be built from source
  + [X] scikit-image was problematic
    + Canopy had version 0.5 for some reason, which is wat to old (didn't have =morpholoy.dilate=, which I use a lot. 
    + The latest version on pypi was 0.8, but this seems to have a bug
    + So grab latest dev version (0.9dev at time of writing)
      #+BEGIN_SRC sh
        cd ~/Source
        git clone http://github.com/scikit-image/scikit-image.git
      #+END_SRC
      And build and install it
      #+BEGIN_SRC sh
        cd ~/Source/scikit-image
        python setup.py build
        python setup.py install
      #+END_SRC
** Fonts
*** Courier Prime
+ http://quoteunquoteapps.com/courierprime/
+ This font was designed for writing movie scripts, but it is a great general-purpose monospace font.
+ It comes with regular, /italic/, *bold*, and /*bold italic*/ versions. 
+ It is much more robust looking than the standard Courier, which always looked too spindly to me.
+ On a retina display, it is perfectly legible as small as 9 pt, although you probably want it bigger than that.
** Utilities
*** Moom - Window Control
*** Mailplane
*** 1Password

** Consumer software

** Astrophysics
